---
title: "Testing Apache Cassandra database throughput for different consistency levels"
output: 
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: true
---
```{r pobieranie bibliotek, message = FALSE, echo = FALSE}
library(ggplot2)
library(plotly)
library(tidyr)
```

```{r ³adowanie danych, echo = FALSE, cache = TRUE}
data <- read.csv2(file = "./result.csv")
data <- data[data$throughput != 0, ]
data_aws <- read.csv(file = "./result_aws.csv")
data_aws_ssd <- read.csv(file = "./result_aws_ssd.csv")
```

#Data summary
```{r podsumowanie, echo = FALSE}
knitr::kable(summary(data))
```

#Workloads description
#####A: 50% read / 50% write
#####B: 95% read / 5% write
#####C: 100% read
#####D: read latest workload
#####F: read-modify-write

#Results in boxplot
```{r result boxplot, fig.height=10, fig.width=10, echo = FALSE}
plot_box <- ggplot(data, aes(x = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")),
                            y = throughput, 
                            fill = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")), 
                            color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_boxplot() +
  facet_grid(workload~nodes) +
  theme(axis.text.x = element_text(angle = 45)) +
  xlab(label = "Consistency level") +
  ylab(label = "Throughput") +
  labs(color = "Consistency level", fill = "Consistency level")

ggplotly(plot_box)
```

#Results in points plot
```{r result points, fig.height=10, fig.width=10, echo = FALSE}
plot_point <- ggplot(data, aes(x = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")),
                            y = throughput, 
                            fill = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")), 
                            color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_point() +
  facet_grid(workload~nodes) +
  theme(axis.text.x = element_text(angle = 45)) +
  xlab(label = "Consistency level") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", fill = "Consistency level")

ggplotly(plot_point)
```

#Results in points plot with jitter
```{r result points jitter, fig.height=10, fig.width=10, echo = FALSE}
plot_point_jit <- ggplot(data, aes(x = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")),
                            y = throughput, 
                            fill = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")), 
                            color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_point(position = "jitter") +
  facet_grid(workload~nodes) +
  theme(axis.text.x = element_text(angle = 45)) +
  xlab(label = "Consistency level") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", fill = "Consistency level")

ggplotly(plot_point_jit)
```

#Results in line plots
```{r result line, fig.height=10, fig.width=10, echo = FALSE}
data_means <- data %>%
  group_by(workload, nodes, consistency_level) %>%
  summarise(throughput = mean(throughput))

plot_line <- ggplot(data_means, aes(x = nodes, 
                                    y = throughput, 
                                    color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_line() +
  geom_point() +
  facet_wrap(~workload) +
  xlab(label = "Nodes") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level")

ggplotly(plot_line)
```

#AWS results in points plot
```{r aws result points, fig.height=7, fig.width=7, echo = FALSE}
plot_point_aws <- ggplot(data_aws, aes(x = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")),
                            y = throughput,
                            fill = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")),
                            color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_point() +
  facet_grid(replicas~nodes, labeller = label_both) +
  theme(axis.text.x = element_text(angle = 45)) +
  xlab(label = "Consistency level") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", fill = "Consistency level")

ggplotly(plot_point_aws)
```

#AWS results in line plot
```{r aws result line, fig.height=5, fig.width=10, echo = FALSE}
plot_line_aws <- ggplot(data_aws, aes(x = nodes, 
                                    y = throughput, 
                                    color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_line() +
  geom_point() +
  facet_wrap(~replicas, labeller = label_both) +
  xlab(label = "Nodes") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", title = "Workload A")

ggplotly(plot_line_aws)
```

#AWS results in line plot
```{r aws result line 2, fig.height=5, fig.width=10, echo = FALSE}
plot_line_aws_2 <- ggplot(data_aws, aes(x = replicas, 
                                    y = throughput, 
                                    color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_line() +
  geom_point() +
  facet_wrap(~nodes, labeller = label_both) +
  xlab(label = "Replicas") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", title = "Workload A")

ggplotly(plot_line_aws_2)
```

#AWS SSD results in line plot
```{r aws ssd result line, fig.height=5, fig.width=10, echo = FALSE}
plot_line_aws_ssd <- ggplot(data_aws_ssd, aes(x = nodes, 
                                    y = throughput, 
                                    color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_line() +
  geom_point() +
  facet_wrap(~replicas, labeller = label_both) +
  xlab(label = "Nodes") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", title = "Workload A")

ggplotly(plot_line_aws_ssd)
```

#AWS SSD results in line plot
```{r aws ssd result line 2, fig.height=5, fig.width=10, echo = FALSE}
plot_line_aws_ssd_2 <- ggplot(data_aws_ssd, aes(x = replicas, 
                                    y = throughput, 
                                    color = factor(consistency_level, levels = c("ANY", "ONE", "TWO", "THREE", "QUORUM", "ALL")))) +
  geom_line() +
  geom_point() +
  facet_wrap(~nodes, labeller = label_both) +
  xlab(label = "Replicas") +
  ylab(label = "Throughput (ops/sec)") +
  labs(color = "Consistency level", title = "Workload A")

ggplotly(plot_line_aws_ssd_2)
```